variable "bucket_name" {
  type        = string
  description = "Name of the S3 bucket in the current (bucket-owner) account."
}

variable "principals" {
  description = "List of IAM roles (possibly across multiple accounts) that should access this bucket."
  type = list(object({
    account_id = string
    role_name  = string
  }))
  default = []
}

variable "access" {
  type        = string
  description = "Access level to grant: 'read' or 'readwrite'. Default: 'read'."
  default     = "read"
  validation {
    condition     = contains(["read", "readwrite"], var.access)
    error_message = "access must be 'read' or 'readwrite'."
  }
}

variable "prefixes" {
  type        = list(string)
  description = "Optional list of allowed prefixes (e.g. ['libs/', 'config/']). Empty = allow all objects."
  default     = []
}

variable "allow_list" {
  type        = bool
  description = "Whether to allow s3:ListBucket (relevant for IAM principals)."
  default     = true
}

variable "existing_policy_json_path" {
  type        = string
  description = "Optional path to existing bucket policy JSON to merge with the policy generated by this module."
  default     = null
}

variable "cloudfront_access" {
  description = "Optional CloudFront (OAC) access rule."
  type = object({
    source_account_id = string
    # Use wildcard to avoid hardcoding distribution id:
    source_arn_like = optional(string) # default computed if omitted
    actions         = optional(list(string), ["s3:GetObject"])
  })
  default = null
}
